### ISSUE TITLE
Thanks! 😁

### ISSUE THREAD

**Issue by praveenscience** [stemount/stemount#1]
Hey Steve! I know I am misusing this GitHub feature, but I don't know what is the better way to thank you for sponsoring me. It means a lot! 😁

I'll make sure I put the money to the right use and keep doing awesome content. Should we do a Live Video together on my channel? Please?

Thanks to @EddieJaoude for letting me know about this! With lots of love! 😻

**Comment by eddiejaoude** [comment]
I want to sponsor @stemount back, but he hasn't enabled it yet 😢

**Comment by praveenscience** [comment]
Oh no, it was too easy for the application @stemount! 👌🏻 Gets enabled like instantly!

**Comment by stemount** [comment]
:) @praveenscience absolutely!! @eddiejaoude I will have all the stuff ready to do something.........

i have some (less ridiculous than reverse engineering Windows apps to ARM/linux things!) -  ideas that i need to stick in a repo for things that the community could make on the live streams!!

💯 
i'm gonna leave this issue open as I still need to "complete" this goal!!!

**Comment by eddiejaoude** [comment]
@stemount sponsors button is there, I sponsored him 🎉 - video coming out this week, editing it at the moment 🤓 (teaser coming on socials in a few hours 😎 )

**Comment by stemount** [comment]
@praveenscience @eddiejaoude open source all the way!!
